name: Copy Secret
on:
  workflow_dispatch:
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy NUGET_API_KEY to PollyMediatR
        env:
          GH_TOKEN: ${{ secrets.COPILOT_GH_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          gh secret set NUGET_API_KEY --repo Swevo/PollyMediatR --body "$NUGET_API_KEY"
          echo "Done"
